### ISSUE TITLE
why derived from cc-mode? 

### ISSUE THREAD

**Issue by daoio** [GokhanPolat/emacs-huff-mode#1]
Hello sir, awesome Major mode, I've used it with pretty much fun! I'm curious why is it derived from `cc-mode`, while `solidity-mode` has a lot of useful keywords that Huff uses too (e.g. payable, view, msg.sender, etc. etc.)?

**Comment by GokhanPolat** [comment]
Hi @daoio,
I did chose cc-mode because solidity-emacs package too derive cc-mode and I was want to start from beginning. Besides easy to adding evm keywords, font locking but hard to creating huff language specific syntax settings. I believe starting with cc-mode more logical way to develoing this package.

**Comment by daoio** [comment]
Got you sir, makes sense!
